platform :ios, '9.0'
inhibit_all_warnings!

use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

target 'WYAKit_Example' do
  pod 'WYAKit', :path => '../'
  pod 'WHDebugTool'
  pod 'MLeaksFinder'
  pod 'NetworkEye', '~> 1.0.1'
  pod 'Bugly'
  target 'WYAKit_Tests' do
    inherit! :search_paths

    
  end
end
