#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = "NO"
    end
  end
end

target 'WYAKit_Example' do
  pod 'WYAKit', :path => '../'
  pod 'WHDebugTool'
  pod 'MLeaksFinder'
  pod 'NetworkEye', '~> 1.0.1'
  pod 'Bugly'
  pod 'ZFPlayer', '~> 3.0'
  pod 'ZFPlayer/ControlView', '~> 3.0'
  pod 'ZFPlayer/AVPlayer', '~> 3.0'
  target 'WYAKit_Tests' do
    inherit! :search_paths

    
  end
end
